export const ADD_LOCATION = "ADD_LOCATION";
export const RESTORE_LOCATIONS = "RESTORE_LOCATIONS";
export const REMOVE_LOCATION = "REMOVE_LOCATION";
export const CHANGE_LOCATIONS = "CHANGE_LOCATIONS";
